const users = [
    {
        id: 1,
        name: 'Sona',
        surname: 'Khachatryan',
        age: 22,
        imageUrl: './assets/users/sona.jpg',
    },
    {
        id: 2,
        name: 'Artush',
        surname: 'Miqayelyan',
        age: 16,
    },
    {
        id: 3,
        name: "Mane",
        surname: "Manukyan",
        age: 23,
        imageUrl: './assets/users/mane.jpg',
    },
    {
        id: 4,
        name: "Levon",
        surname: "Babaian",
        age: 20,
        imageUrl: './assets/users/levon.jpg',
    },
    {
        id: 5,
        name: 'Aram',
        surname: 'Antonyan',
        age: 24,
        imageUrl: './assets/users/aram.jpg',
    },
    {
        id: 6,
        name: 'Ofelya',
        surname: 'Terteryan',
        age: 28,
        imageUrl: './assets/users/ofelya.jpg',
    },
    {
        id: 7,
        name: "Gohar",
        surname: "Papoyan",
        age: 30,
        imageUrl: './assets/users/gohar.jpg',
    },
    {
        id: 8,
        name: 'Aren',
        surname: 'Muradyan',
        age: 22,
        imageUrl: './assets/users/aren.png',
    },
    {
        id: 9,
        name: "Rafael",
        surname: "Farkhoyan",
        age: 32,
        imageUrl: './assets/users/rafayel.jpg',
    },
    {
        id: 10,
        name:"Davit",
        surname:"Gasparyan",
        age: 21,
        imageUrl: './assets/users/davit.png',
    },
    {
        id: 11,
        name:"Gevorg",
        surname:"Sargsyan",
        age: 26,
        imageUrl: './assets/users/gevorg.jpg',
    },
    {
        id: 12,
        name: 'Ani',
        surname: 'Khanamiryan',
        age: 16,
        imageUrl: './assets/users/ani.jpg',
    },
    {
        id: 13,
        name: 'Sergey',
        surname: 'Amiraghyan',
        age: 28,
        imageUrl: './assets/users/sergey.jpg',
    },
    {
        id: 14,
        name: 'Erik',
        surname: 'Ghazaryan',
        age: 17,
        imageUrl: './assets/users/erik.jpg',
    }
]

export { users };